version: "3.7"
services:

  web:
    build: .
    ports:
      - 80:80
    depends_on: 
      - mysql
    environment: 
      MYSQL_HOST: mysql
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: db_databasename
    volumes:
    - ./app:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_DATABASE: db_databasename
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  
