version: "3.7"
services:

  web:
    build: .
    ports:
      - 80:80
    depends_on: 
      - mysql
    env_file:
      - ./env/environment.env
    volumes:
    - ./app:/var/www/html

  mysql:
    image: mysql:5.7
    env_file:
      - ./env/environment.env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  
